extends: airbnb
installedESLint: true
env:
  browser: true
  jasmine: true
  mocha: true
plugins:
  - react
import/resolver:
  jspm: { moduleDirectory: public/jspm_packages }
  node: true
rules:
  class-methods-use-this: off
  no-useless-constructor: off
  spaced-comment: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/extensions: off
  react/prefer-stateless-function: 2
  react/jsx-filename-extension: 2
  react/require-extension: off
  react/prop-types: off
