version: '2'

services:
  web:
    build: .
    ports:
    - "80:3000"
    volumes:
      - ./db:/home/seminovos/db
    command: npm run start

  crawler:
    build: .
    volumes:
      - ./db:/home/seminovos/db
    command: npm run crawler

